# Generated by Django 4.2.2 on 2023-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safo_eshiklar', '0003_remove_products_price_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='No',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
